-- Camada silver de RECEITAS
create table if not exists silver_receitas (
    cd_receita           text,
    cd_categoria         text,
    descricao_categoria  text,
    cd_origem            text,
    descricao_origem     text,
    cd_especie           text,
    descricao_especie    text,
    cd_rubrica           text,
    descricao_rubrica    text,
    cd_alinea            text,
    descricao_alinea     text,
    cd_subalinea         text,
    descricao_subalinea  text,
    cd_exercicio         text,
    dt_apropriacao       date,
    ano_exercicio        integer,
    mes_apropriacao      integer,
    tp_receita_orc       text,
    cd_empresa           text,
    nm_empresa           text,
    vl_receita           numeric(16,2),
    ds_fonte             text
);

truncate table silver_receitas;

insert into silver_receitas (
    cd_receita,
    cd_categoria,
    descricao_categoria,
    cd_origem,
    descricao_origem,
    cd_especie,
    descricao_especie,
    cd_rubrica,
    descricao_rubrica,
    cd_alinea,
    descricao_alinea,
    cd_subalinea,
    descricao_subalinea,
    cd_exercicio,
    dt_apropriacao,
    ano_exercicio,
    mes_apropriacao,
    tp_receita_orc,
    cd_empresa,
    nm_empresa,
    vl_receita,
    ds_fonte
)
select
    cd_receita,
    cd_categoria,
    descricao_categoria,
    cd_origem,
    descricao_origem,
    cd_especie,
    descricao_especie,
    cd_rubrica,
    descricao_rubrica,
    cd_alinea,
    descricao_alinea,
    cd_subalinea,
    descricao_subalinea,
    cd_exercicio,
    dt_apropriacao,
    nullif(cd_exercicio, '')::integer as ano_exercicio,
    extract(month from dt_apropriacao)::integer as mes_apropriacao,
    tp_receita_orc,
    cd_empresa,
    nm_empresa,
    vl_receita,
    ds_fonte
from stg_receitas;


-- Camada silver de DESPESAS
create table if not exists silver_despesas (
    ano_empenho               text,
    ano_empenho_int           integer,
    dt_empenho                date,
    mes_empenho               integer,
    empresa                   text,
    sigla_empresa             text,
    cd_orgao                  text,
    ds_orgao                  text,
    sigla_orgao               text,
    cd_unidade                text,
    ds_unidade                text,
    sigla_unidade             text,
    cd_funcao                 text,
    ds_funcao                 text,
    cd_subfuncao              text,
    ds_subfuncao              text,
    cd_programa               text,
    ds_programa               text,
    cd_acao                   text,
    ds_acao                   text,
    cd_categoria_despesa      text,
    ds_categoria_despesa      text,
    cd_grupo_despesa          text,
    ds_grupo_despesa          text,
    cd_modalidade_despesa     text,
    ds_modalidade_despesa     text,
    cd_elemento_despesa       text,
    ds_elemento_despesa       text,
    cd_subelemento_despesa    text,
    ds_subelemento_despesa    text,
    cd_fonte                  text,
    ds_fonte                  text,
    fornecedor                text,
    cpf_cnpj                  text,
    nr_empenho                text,
    licitacao                 text,
    orcado_inicial_empenho    numeric(16,2),
    orcado_atual_empenho      numeric(16,2),
    vl_empenhado              numeric(16,2),
    protocolosup              text,
    dt_transacao              date,
    nr_parcela                text,
    transacao                 text,
    vl_liquidado              numeric(16,2),
    vl_pago_devolvido         numeric(16,2),
    vl_emp_anulado            numeric(16,2),
    vl_pago                   numeric(16,2),
    vl_consignado             numeric(16,2)
);

truncate table silver_despesas;

insert into silver_despesas (
    ano_empenho,
    ano_empenho_int,
    dt_empenho,
    mes_empenho,
    empresa,
    sigla_empresa,
    cd_orgao,
    ds_orgao,
    sigla_orgao,
    cd_unidade,
    ds_unidade,
    sigla_unidade,
    cd_funcao,
    ds_funcao,
    cd_subfuncao,
    ds_subfuncao,
    cd_programa,
    ds_programa,
    cd_acao,
    ds_acao,
    cd_categoria_despesa,
    ds_categoria_despesa,
    cd_grupo_despesa,
    ds_grupo_despesa,
    cd_modalidade_despesa,
    ds_modalidade_despesa,
    cd_elemento_despesa,
    ds_elemento_despesa,
    cd_subelemento_despesa,
    ds_subelemento_despesa,
    cd_fonte,
    ds_fonte,
    fornecedor,
    cpf_cnpj,
    nr_empenho,
    licitacao,
    orcado_inicial_empenho,
    orcado_atual_empenho,
    vl_empenhado,
    protocolosup,
    dt_transacao,
    nr_parcela,
    transacao,
    vl_liquidado,
    vl_pago_devolvido,
    vl_emp_anulado,
    vl_pago,
    vl_consignado
)
select
    ano_empenho,
    nullif(ano_empenho, '')::integer as ano_empenho_int,
    dt_empenho,
    extract(month from dt_empenho)::integer as mes_empenho,
    empresa,
    sigla_empresa,
    cd_orgao,
    ds_orgao,
    sigla_orgao,
    cd_unidade,
    ds_unidade,
    sigla_unidade,
    cd_funcao,
    ds_funcao,
    cd_subfuncao,
    ds_subfuncao,
    cd_programa,
    ds_programa,
    cd_acao,
    ds_acao,
    cd_categoria_despesa,
    ds_categoria_despesa,
    cd_grupo_despesa,
    ds_grupo_despesa,
    cd_modalidade_despesa,
    ds_modalidade_despesa,
    cd_elemento_despesa,
    ds_elemento_despesa,
    cd_subelemento_despesa,
    ds_subelemento_despesa,
    cd_fonte,
    ds_fonte,
    fornecedor,
    cpf_cnpj,
    nr_empenho,
    licitacao,
    orcado_inicial_empenho,
    orcado_atual_empenho,
    vl_empenhado,
    protocolosup,
    dt_transacao,
    nr_parcela,
    transacao,
    vl_liquidado,
    vl_pago_devolvido,
    vl_emp_anulado,
    vl_pago,
    vl_consignado
from stg_despesas;
